import Vue from 'vue'
import	AutoComplete	 from  './AutoComplete/AutoComplete.vue'
import	Avatar	 from  './Avatar/Avatar.vue'
import	BackTop	 from  './BackTop/BackTop.vue'
import	Breadcrumb	 from  './Breadcrumb/Breadcrumb.vue'
import	Carousel	 from  './Carousel/Carousel.vue'
import	Cascader	 from  './Cascader/Cascader.vue'
import	Checkbox	 from  './Checkbox/Checkbox.vue'
import	Dropdown	 from  './Dropdown/Dropdown.vue'
import	Editor	 from '../Common/pc/Editor/Editor.vue'
import	Menu	 from  './Menu/Menu.vue'
import	Option	 from  './Option/Option.vue'
import	Poptip	 from  './Poptip/Poptip.vue'
import	Progress	 from  './Progress/Progress.vue'
import	Radio	 from  './Radio/Radio.vue'
import	Scroll	 from  './Scroll/Scroll.vue'
import	Select	 from  './Select/Select.vue'
import	Spin	 from  './Spin/Spin.vue'
import	Steps	 from  './Steps/Steps.vue'
import	Tabs	 from  './Tabs/Tabs.vue'
import	TimelineItem	 from  './TimelineItem/TimelineItem.vue'
import	Tooltip	 from  './Tooltip/Tooltip.vue'
import	Transfer	 from  './Transfer/Transfer.vue'
import	UploadFile	 from  './UploadFile/UploadFile.vue'
import	UploadImg	 from  './UploadImg/UploadImg.vue'


Vue.component(	AutoComplete.name, AutoComplete	)
Vue.component(	Avatar.name, Avatar	)
Vue.component(	BackTop.name, BackTop	)
Vue.component(	Breadcrumb.name, Breadcrumb	)
Vue.component(  Carousel.name, Carousel )
Vue.component(	Cascader.name, Cascader	)
Vue.component(	Checkbox.name, Checkbox	)
Vue.component(	Dropdown.name, Dropdown	)
Vue.component(	Editor.name, Editor	)
Vue.component(	Menu.name, Menu	)
Vue.component(	Option.name, Option	)
Vue.component(	Poptip.name, Poptip	)
Vue.component(	Progress.name, Progress	)
Vue.component(	Radio.name, Radio	)
Vue.component(	Scroll.name, Scroll	)
Vue.component(	Select.name, Select	)
Vue.component(	Spin.name, Spin	)
Vue.component(	Steps.name, Steps	)
Vue.component(	Tabs.name, Tabs	)
Vue.component(	TimelineItem.name, TimelineItem	)
Vue.component(	Tooltip.name, Tooltip	)
Vue.component(	Transfer.name, Transfer	)
Vue.component(	UploadFile.name, UploadFile	)
Vue.component(	UploadImg.name, UploadImg	)